### ISSUE TITLE
code readability/formatting

### ISSUE THREAD

**Issue by ad3429** [newbwspjjy/bwa-u3-jammming-prj#1]
https://github.com/newbwspjjy/bwa-u3-jammming-prj/blob/master/src/components/App/App.js#L1-L90

It might be a good idea to install an extension that automatically formats your JS code for you to make it more organized and readable. Here's one good example:

https://prettier.io/

Your code formatting/indentation seems quite inconsistent at times and so this would allow you to not have to worry about formatting as it's done automatically.

**Comment by newbwspjjy** [comment]
Done, installed prettier. Thank you for the heads up @ad3429 , been wondering which to use, prettier or linter.
